### ISSUE TITLE
Are you intend to support it for Codeigniter 3

### ISSUE THREAD

**Issue by aa6my** [xiidea/ezRbac#19]
Would be appreciate.

**Comment by ronisaha** [comment]
Yes have plan for that

**Comment by schorschie** [comment]
This may be a stupid question, but does it not work in general with CodeIgniter 3.0.3 ? I'm trying to run it on my localhost, but when going to /rbac/gui I route to my welcome message :(

**Comment by ronisaha** [comment]
@schorschie :  As of  CodeIgniter 3 the file name convention hasbeen changed, so for current release it may not work on linux machine. but it should still work on windows machine. You can rename all the class file as ucfirst (Like ezuri->Ezuri ). then it should work

**Comment by aa6my** [comment]
thanks @ronisha

**Comment by ronisaha** [comment]
Library updated to support CI-3
