### ISSUE TITLE
Permision access Login To manage ACL

### ISSUE THREAD

**Issue by Rajeshwar90** [xiidea/ezRbac#21]
Hi Ronisha,
Hope the question is not that silly,
1) when I hit index.php  the URL for ezRbac opens which logsin with the credentials that you have mentioned in the latest Github repository of Ezrbac. what is this URL for 
Login To manage ACL?? URL: "http://localhost/CodeIgniter/index.php/rbac/gui"

2) what will be the creddentials for thiis rbac/gui ?

**Comment by ronisaha** [comment]
1) http://localhost/CodeIgniter/index.php/**{DEFAULT_CONTROLLER}**/index/rbac/login if the default controller is **`welcome`** then the Url wolud be: http://localhost/CodeIgniter/index.php/**welcome**/index/rbac/login . you can find the [reference here](http://xiidea.github.io/ezRbac/#ezrbac-specific-url)

2) You can configure the gui password. default is: **hardtoremember** https://github.com/xiidea/ezRbac/blob/master/config/ez_rbac.php#L91

**Comment by Rajeshwar90** [comment]
Hi Roni,
Thanks for the reply.We found that ezRbac was supporting for the codeigniter version 2.1. Do we have an updated version of EzRbac that supports the latest codeigniter 3.1.
Or are you aware of any such ACL for easy codeigniter plugin?

Any help will be appreciated.Thanks.

**Comment by ronisaha** [comment]
I've plan to update the library for CI-3. Hope I'll release a version soon
