### ISSUE TITLE
How to login?Not acl manage.

### ISSUE THREAD

**Issue by yukunwu** [xiidea/ezRbac#23]
Hi,
   Thanks for the great project.
   I can login to acl manage page by visit '{server_name}/{default_controller}/index/rbac/gui',but i can't find normal login page.I see that there is view pages in /application/views/login/ folder,and it's used in libraries/Ezlogin.php.I read through the code and the guides,not found where to login.

What is that?

**Comment by ronisaha** [comment]
Hi,
The login page will be served when you access any restricted page and you do not need any different url for login page.

**Comment by yukunwu** [comment]
yeah,
    I don't know why formerly it didn't redirect to the login page,I have tried many times.
    Never mind,it works now.
Cool.
