### ISSUE TITLE
ACL Management Page Not Open

### ISSUE THREAD

**Issue by ntperdana** [xiidea/ezRbac#27]
Hi There,

I was wondering if I would get help from you . I am interested in using your module in my existing CodeIgniter based project and I have carefully followed your instructions published in https://github.com/xiidea/ezRbac. However, I always get an error after filling out the "hardtoremember" password. Please see the screenshot for the error details.

Are there any missing steps in the instructions which could possibly cause this error? Look forward to hearing from you.

Thanks in advance.

<img width="957" alt="screen shot 2017-07-05 at 3 22 20 am" src="https://user-images.githubusercontent.com/29901424/27842123-33349532-6131-11e7-8d37-12cf9c3b9f4c.png">
<img width="888" alt="screen shot 2017-07-05 at 3 22 11 am" src="https://user-images.githubusercontent.com/29901424/27842125-33825682-6131-11e7-8d03-9a8b30e518fe.png">
<img width="868" alt="screen shot 2017-07-05 at 3 22 01 am" src="https://user-images.githubusercontent.com/29901424/27842124-337f9780-6131-11e7-9f87-deb65af9024e.png">

**Comment by ronisaha** [comment]
Could you please provide some more information. Like:
Which CI version
PHP version
Library version.

**Comment by ntperdana** [comment]
Hi Roni,

Thanks for reaching out to me so prompt.

Honestly speaking, I am not an experienced developer but I was interested in using your module due to the clear installation guide. Let me try to answer your question as complete as possible.

- CI Version: 3.1.0
- PHP Version: 7.0.16
- Library Version: Do you mean the ezRbac libraries version? I tried to open ezRbac/libraries/Ezlogin.php and here is the output. 

 * @version    1.2
 * @package    ezRbac
 * @since      ezRbac v 0.3
 * @author     Roni Kumar Saha<roni.cse@gmail.com>
 * @copyright  Copyright &copy; 2012 Roni Saha
 * @license    GPL v3 - http://www.gnu.org/licenses/gpl-3.0.html <http://www.gnu.org/licenses/gpl-3.0.html>

Hope to hear from you soon.
 
Thanks.

Kind Regards,



Dana
+6282125686505
www.cloudbanget.com
Solusi Cloud Murah dan Handal, 
Cuma Di CloudBanget Tempatnya.

**Comment by ronisaha** [comment]
This was a issue with PHP version 7. Has been fixed in master branch

**Comment by ntperdana** [comment]
Hi Roni,

I am sorry for asking again. The issue with ACL page is indeed solved in the current Master Branch. However, I do have other issue as follows. Please advise if I need to open a new thread for this.

- How do we add users? If required to inject manually, what is the "salt" column for in the table system_users?
- How do we add user Roles? If required to inject manually, what is the "default_access" column in the table user_role? How does "default_access" column relate to the user_roles_id?
- Once I login to the ACL page, I noticed that Role Admin has "view" access for all controllers by default. Then, I uncheck "view" checkbox for Admin in one controller, I add the function "access_map" in that controller (with array value: 'index'=>'view'). The result is that I can still go into that controller page even though the checkbox is unchecked. However, if I change the array value to be  ('index'=>'edit') in that controller and check the "edit" checkbox and leave the "view" checkbox unchecked from the ACL page for admin, the result is I cannot go into that controller anymore. Could you please help me to understand how I should play around with these roles?
 
Thanks.

Kind Regards,



Dana
+6282125686505
www.cloudbanget.com
Solusi Cloud Murah dan Handal, 
Cuma Di CloudBanget Tempatnya.

**Comment by ronisaha** [comment]
Please read the [documentation](https://github.com/xiidea/ezRbac/blob/master/docs/api.md). Feel free to ask if you need more help.

-Happy coding

**Comment by ntperdana** [comment]
Hi Roni,

What about the last question i asked? Any more clues you can give me? It seems that whatever permissions I check in the ACL page for Admin, I can go to a controller only when that controller has access_map function with an array containing 'index'=>'view.

Thanks in advance.

My original question:

- Once I login to the ACL page, I noticed that Role Admin has "view" access for all controllers by default. Then, I uncheck "view" checkbox for Admin in one controller, I add the function "access_map" in that controller (with array value: 'index'=>'view'). The result is that I can still go into that controller page even though the checkbox is unchecked. However, if I change the array value to be  ('index'=>'edit') in that controller and check the "edit" checkbox and leave the "view" checkbox unchecked from the ACL page for admin, the result is I cannot go into that controller anymore. Could you please help me to understand how I should play around with these roles?
 


This email is sent from my mobile device. Please accept my sincere apology for any possible typos in this email.

Kind regards, 



Dana
Presales Manager | Presales Dvision
Mobile: +6282125686505| Email: novarica.perdana@mastersystem.co.id

**Comment by ronisaha** [comment]
> Once I login to the ACL page, I noticed that Role Admin has "view" access for all controllers by default.

I don't remember why but I while i designed the library in some point i set the default access for a controller which access role is not configured set to view. You can change the value in [here](https://github.com/xiidea/ezRbac/blob/master/libraries/Accessmap.php#L33-L38) 

> Then, I uncheck "view" checkbox for Admin in one controller, I add the function "access_map" in that controller (with array value: 'index'=>'view'). The result is that I can still go into that controller page even though the checkbox is unchecked. 

 **This is also a bug for CI 3. I'll fix this on next update.**

However, if I change the array value to be  ('index'=>'edit') in that controller and check the "edit" checkbox and leave the "view" checkbox unchecked from the ACL page for admin, the result is I cannot go into that controller anymore. Could you please help me to understand how I should play around with these roles?

Hope the bug(s) will be fixed on next update. when i can make time(not before next two day)

Thanks for finding these issues.

Happy coding.

**Comment by ntperdana** [comment]
Hi Roni,

Sorry for replying again. I was about to wait, but you seem to have updated the thread.

What I understand right now is that $_default_access in libraries/Accessmap.php overrides all the settings saved in database. Meaning to say, if open up a controller, it will always use $_default_access as the permission set. How do I test it? Please look the following list:

1. I understand that $_default_access can be configured like binary numbers. So by default, there are 5 permission, $_default_access should be configured as xxxxx where x is either 1 or 0.
2. For testing, i use different $_default_access (1-31)to see the impact to the overall system. To my understanding, $_default_access should only be used if there are no data in the table user_access_map. But in fact, $_default_access is always used although there are permission information in the table. 

Could you please point me out where I should look into to ensure that everytime a page/controller is loaded, ezRbac module will first get the permission information from the database? I think there is something missing in that.

I hope I am making myself clear to you and hope to hear from you agin. :)
 
Thanks.

Kind Regards,



Dana
+6282125686505
www.cloudbanget.com
Solusi Cloud Murah dan Handal, 
Cuma Di CloudBanget Tempatnya.

**Comment by ntperdana** [comment]
Hi Roni,

Just want to give you an update, I did the following change and it seems to work. Maybe if you have time, you may verify and confirm whether this is the final fix and can be updated in the next release. 


File libraries/Accessmap.php

    private function get_permission($controller, $access_role = FALSE)
    {
        if (!$access_role && !$this->CI->session->userdata($this->_login_session_key)) {
            echo "should not be here";
            return FALSE;
        }

        if (!$access_role) {
            $access_role = $this->CI->session->userdata('access_role');
        }

        $this->CI->load->model('user_access_map');
-        $permission = $this->CI->user_access_map->get_permission($access_role, $controller);
+        $permission = $this->CI->user_access_map->get_permission($access_role, ucfirst($controller));

        if (is_null($permission)) {
            return $this->_default_access;
        }

        return (int)$permission;
    }

Thanks.

Kind Regards,



Dana
+6282125686505
www.cloudbanget.com
Solusi Cloud Murah dan Handal, 
Cuma Di CloudBanget Tempatnya.

**Comment by ronisaha** [comment]
Your change will not work, suppose you have a controller in admin sub directory: `admin/Welcome.php` then your ucfirst check will leads to you to `Admin/welcome.php` which is not correct. My update was to save the data in lower case format. Please check with the latest code if its working or not.

**Comment by ntperdana** [comment]
Hi Roni,

Just tried your latest changes. It seems to work now, thanks alot for the help! 


This email is sent from my mobile device. Please accept my sincere apology for any possible typos in this email.

Kind regards, 



Dana
Presales Manager | Presales Dvision
Mobile: +6282125686505| Email: novarica.perdana@mastersystem.co.id
