### ISSUE TITLE
How to run 

### ISSUE THREAD

**Issue by chandhanm20** [xiidea/ezRbac#32]
what changes need to do on routes.php file

**Comment by ronisaha** [comment]
Read the [documentation here](http://xiidea.github.io/ezRbac/#ezrbac-specific-url)

**Comment by chandhanm20** [comment]
Ya I read that .. I implemented this Rbac library in my Codeigniter application .. but I dint found exactly how to run this .. please anyone help me .. and send URL of the welcome page

**Comment by ronisaha** [comment]
Could you please clarify your question? How to use the library is documented [here](http://xiidea.github.io/ezRbac/) . If you have any specific use case/error/problem/question please add some details.

**Comment by chandhanm20** [comment]
I saw that documentation .. but send the URL to run that application after implementing Rbac library

**Comment by ronisaha** [comment]
@chandhanm20 : What URL?

**Comment by chandhanm20** [comment]
to run the application in my local host i need URL right .. so please send the URL for that ..

**Comment by chandhanm20** [comment]
if i give localhost/myapplication_name/index.php/rbac .. I'm not getting

**Comment by ronisaha** [comment]
http://localhost/myapplication_name/index.php/

**Comment by ivankusuma07** [comment]
what is the view when I access /index.php/welcome/index/rbac/gui? it always bring me to the default controller.

**Comment by ronisaha** [comment]
which ci version you are using? I've not tested the library quite a log period with latest ci releases.

**Comment by ivankusuma07** [comment]
3.1.9. It can be accessed  now. but the assets can't show.

**Comment by ivankusuma07** [comment]
fixed.. forget to place .htaccess file to root.
