### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by tejkweku** [xiidea/ezRbac#33]
I have tried installing the ezRbac pakcage in my `CodeIgniter -3.1.10` installation by following the 5-step procedure. However, I receive this error anytime I try to access any URL after the installing the package (including `http://{server_name}/{project_name}/index.php/welcome/index/rbac/gui`)

![ezRbac install error](https://user-images.githubusercontent.com/7029109/55683488-3db7b100-5938-11e9-8a1d-27239797a8a7.png)

I request how to go about fixing this issue. Thanks.

**Comment by ronisaha** [comment]
It is related to your db configuration. Try to access database from your application, without using this library. If everything works, then use this library.

solution by guessing:
Change dns value from `application/config/database.php`
```code
'dsn'	=> 'host=DB_HOST;dbname=DATABASE_NAME',
```
to 
```
'dsn'	=> 'mysql:host=DB_HOST;dbname=DATABASE_NAME',
```
